### ISSUE TITLE
featurerequest или needhelp синхронизация по времени выключателя и сегментов трека

### ISSUE THREAD

**Issue by mike1s** [krakrukra/LocalTrack#1]
Здравствуйте. Спасибо за разработку! Подскажите, пожалуйста. Колхожу устройство, панорамную камеру, в которой мне очень бы помогло не бороться с ленью если бы логгер заканчивал и начинал треки (или сегменты) ровно до секунды с выключателем (с фиксацией, можно дополнительным, вторые контакты включают интервальную съёмку на камерах), или хотя бы только начинал с уже предварительно включёным Гпс- модулем сразу готовым выдавать координаты, или только заканчивал но не выключал Гпс чтобы к следующему включению координаты были сразу, или хотя бы что- нибудь для автоматизированной синхронизации с фотками. Есть ли какие- нибудь простые возможности? Смдшки паяю.

**Comment by krakrukra** [comment]
Извиняюсь за долгий ответ, просто уведомлений никаких не приходило. Случайно зашёл в репозиторий и увидел вопрос.
Я так понимаю речь идёт о том чтобы сделать такой режим где логгер всегда включён, но записывает маршрут только если нажат выключатель. С тем выключателем который уже встроен в устройство это не получится, он так стоит в схеме что может только включать или выключать питание. В принципе, если есть возможность, можно где-то в корпусе выпилить новую дырку под новый выключатель и проводами/проволокой подключить его к свободной ножке микроконтроллера и к земле. Тогда можно будет прописать в прошивке нужное поведение в соответствии с состоянием второго переключателя. Это наверное самый быстрый и простой вариант. 
Ну а вообще у меня была раньше идея допилить какой-нибудь USB-serial интерфейс чтобы можно было в режиме реального времени ловить данные с логгера на компьютер/телефон по проводу USB, возможно передавать команды для включения/выключения итд. Если есть интерес то можно достать эту идею из небытия и всё-таки сделать, но это займёт довольно много времени и  будет не скоро

**Comment by mike1s** [comment]
Понятно. Спасибо за ответ. Я ещё подумаю и позже напишу
